#!/usr/bin/env python
import os
import commands
import sys

def d(tuple):
    out = tuple[1]
    if out:
         print out

def die(msg):
    """Quit and provide error message"""
    print msg
    sys.exit(1)

def main():
    """Call dd and mklab5fs on an existing file"""
    d(commands.getstatusoutput("dd if=/dev/zero of=image bs=1024 count=10240"))
    d(commands.getstatusoutput("./mklab5fs image"))
    return 0

if __name__ == "__main__":
    sys.exit(main())
